version: '2'
services:
  server:
    restart: always
    image: nginx
    volumes:
      - ./server/conf.d:/etc/nginx/nginx.conf
    links:
      - app:app
    ports:
      - "8002:8002"
  app:
    expose:
      - "8002"
    command: gunicorn bitcoin-dashboard:server -b :8002 --name app -w 1 -t 240 --reload --log-file '-' --access-logfile '-'
    restart: always
    build: .
    working_dir: /src
    volumes:
      - ./src:/src
      - ./data:/data
    environment:
      - MODE=dev
